CREATE TABLE IF NOT EXISTS hello (
    id INT generated by default as identity PRIMARY KEY,
    val VARCHAR(20) NOT NULL
);

MERGE INTO hello VALUES (0, 'ボンジュール');
MERGE INTO hello VALUES (1, 'アンニョンハセヨ');
MERGE INTO hello VALUES (2, 'グーテンターク');
MERGE INTO hello VALUES (3, 'チャオ');
MERGE INTO hello VALUES (4, 'ナマステー');
